export const PATIENT_AUTH_REQUEST =  "PATIENT_AUTH_REQUEST"
export const PATIENT_AUTH_SUCCESS =  "PATIENT_AUTH_SUCCESS"
export const PATIENT_AUTH_FAIL =  "PATIENT_AUTH_FAIL"
export const PATIENT_AUTH_LOGOUT =  "PATIENT_AUTH_LOGOUT"

export const DOCTOR_AUTH_REQUEST =  "DOCTOR_AUTH_REQUEST"
export const DOCTOR_AUTH_SUCCESS =  "DOCTOR_AUTH_SUCCESS"
export const DOCTOR_AUTH_FAIL =  "DOCTOR_AUTH_FAIL"
export const DOCTOR_AUTH_LOGOUT =  "DOCTOR_AUTH_LOGOUT"
