// PATIENT AUTHENTICATION
export const PATIENT_AUTH_REQUEST =  "PATIENT_AUTH_REQUEST"
export const PATIENT_AUTH_SUCCESS =  "PATIENT_AUTH_SUCCESS"
export const PATIENT_AUTH_FAIL =  "PATIENT_AUTH_FAIL"
export const PATIENT_AUTH_LOGOUT =  "PATIENT_AUTH_LOGOUT"

export const PATIENT_SIGNIN_REQUEST =  "PATIENT_SIGNIN_REQUEST"
export const PATIENT_SIGNIN_SUCCESS =  "PATIENT_SIGNIN_SUCCESS"
export const PATIENT_SIGNIN_FAIL =  "PATIENT_SIGNIN_FAIL"
export const PATIENT_SIGNIN_LOGOUT =  "PATIENT_SIGNIN_LOGOUT"

// DOCTOR AUTHENTICATION
export const DOCTOR_AUTH_REQUEST =  "DOCTOR_AUTH_REQUEST"
export const DOCTOR_AUTH_SUCCESS =  "DOCTOR_AUTH_SUCCESS"
export const DOCTOR_AUTH_FAIL =  "DOCTOR_AUTH_FAIL"
export const DOCTOR_AUTH_LOGOUT =  "DOCTOR_AUTH_LOGOUT"

export const DOCTOR_SIGNIN_REQUEST =  "DOCTOR_SIGNIN_REQUEST"
export const DOCTOR_SIGNIN_SUCCESS =  "DOCTOR_SIGNIN_SUCCESS"
export const DOCTOR_SIGNIN_FAIL =  "DOCTOR_SIGNIN_FAIL"
export const DOCTOR_SIGNIN_LOGOUT =  "DOCTOR_SIGNIN_LOGOUT"

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST"
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL"

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST'
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS'
export const RESEND_OTP_FAIL = 'RESEND_OTP_FAIL'

export const LOAD_DOCTOR_REQUEST = "LOAD_DOCTOR_REQUEST"
export const LOAD_DOCTOR_SUCCESS = "LOAD_DOCTOR_SUCCESS"
export const LOAD_DOCTOR_FAIL = "LOAD_DOCTOR_FAIL"

export const SEARCH_DOCTORS_REQUEST= "SEARCH_DOCTORS_REQUEST"
export const SEARCH_DOCTORS_SUCCESS= "SEARCH_DOCTORS_SUCCESS"
export const SEARCH_DOCTORS_FAIL= "SEARCH_DOCTORS_SUCCESS"

export const FETCH_DOCTOR_DETAILS_REQUEST = 'FETCH_DOCTOR_DETAILS_REQUEST';
export const FETCH_DOCTOR_DETAILS_SUCCESS = 'FETCH_DOCTOR_DETAILS_SUCCESS';
export const FETCH_DOCTOR_DETAILS_FAIL = 'FETCH_DOCTOR_DETAILS_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS"



// APPOINTMENT
export const FETCH_APPOINTMENTS_REQUEST = 'FETCH_APPOINTMENTS_REQUEST'
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS'
export const FETCH_APPOINTMENTS_FAILURE = 'FETCH_APPOINTMENTS_FAILURE'