// PATIENT AUTHENTICATION
export const PATIENT_AUTH_REQUEST =  "PATIENT_AUTH_REQUEST"
export const PATIENT_AUTH_SUCCESS =  "PATIENT_AUTH_SUCCESS"
export const PATIENT_AUTH_FAIL =  "PATIENT_AUTH_FAIL"
export const PATIENT_AUTH_LOGOUT =  "PATIENT_AUTH_LOGOUT"

export const PATIENT_SIGNIN_REQUEST =  "PATIENT_SIGNIN_REQUEST"
export const PATIENT_SIGNIN_SUCCESS =  "PATIENT_SIGNIN_SUCCESS"
export const PATIENT_SIGNIN_FAIL =  "PATIENT_SIGNIN_FAIL"
export const PATIENT_SIGNIN_LOGOUT =  "PATIENT_SIGNIN_LOGOUT"

// DOCTOR AUTHENTICATION
export const DOCTOR_AUTH_REQUEST =  "DOCTOR_AUTH_REQUEST"
export const DOCTOR_AUTH_SUCCESS =  "DOCTOR_AUTH_SUCCESS"
export const DOCTOR_AUTH_FAIL =  "DOCTOR_AUTH_FAIL"
export const DOCTOR_AUTH_LOGOUT =  "DOCTOR_AUTH_LOGOUT"

export const DOCTOR_SIGNIN_REQUEST =  "DOCTOR_SIGNIN_REQUEST"
export const DOCTOR_SIGNIN_SUCCESS =  "DOCTOR_SIGNIN_SUCCESS"
export const DOCTOR_SIGNIN_FAIL =  "DOCTOR_SIGNIN_FAIL"
export const DOCTOR_SIGNIN_LOGOUT =  "DOCTOR_SIGNIN_LOGOUT"

// DOCTOR VERIFICATION 
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';
export const VERIFY_FILE_REQUEST = 'VERIFY_FILE_REQUEST';
export const VERIFY_FILE_SUCCESS = 'VERIFY_FILE_SUCCESS';
export const VERIFY_FILE_FAILURE = 'VERIFY_FILE_FAILURE';