import React from 'react'
import Navbar from '../Landing Page/Navbar'
import { Link } from 'react-router-dom'
import Footer from '../Landing Page/Footer'

const Terms_Conditions = () => {
  return (
    <div>
      <Navbar />
      <div className='font-Mulish flex items-center justify-center lg:mt-[3rem] xs:mt-[1rem]'>
        <div className='lg:px-[240px] xs:px-[10px]'>
          <h1 className='lg:text-[45px] xs:text-[28px] text-[#000] font-bold'>CareSync Med Website Terms of Use</h1>
          <h2 className='mt-5 font-normal'>Last updated: June 1st, 2024. </h2>
          <h2 className='text-[20px] font-bold mt-5'>1. Introduction</h2>
          <h2 className='mt-1'>Welcome to CareSync Med. By accessing and using our website, you agree to comply with and be bound by the following terms and conditions. Please review them carefully.</h2>
          <h2 className='text-[20px] font-bold mt-5'>2. Definitions</h2>
          <h2 className='mt-1'>The Term “Company”, “we”, “us”, “our” refers to CareSync Med. A “User”, “you”, “your” refers to the person accessing or using the website as a patient. A “Services” refers to the healthcare-related services offered by CareSync Med. “Website” refers to www.caresyncmed.com.</h2>
          <h2 className='text-[20px] font-bold mt-5'>3. Acceptance of Terms</h2>
          <h2 className='mt-1'>‍This Agreement is between you and Caresync Med Corporation.</h2>
          <h2 className='mt-[2rem] font-light'>THIS AGREEMENT CONTAINS WARRANTY DISCLAIMERS AND OTHER PROVISIONS THAT LIMIT OUR LIABILITY TO YOU. PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY AND IN THEIR ENTIRETY, AS USING, ACCES SING, AND/OR BROWSING OUR PLATFORM CONSTITUTES ACCEPTANCE OF THESE TERMS AND CONDITIONS. IF YOU DO NOT AGREE TO BE BOUND TO EACH AND EVERY TERM AND CONDITION SET FORTH HEREIN, PLEASE EXIT OUR PLATFORM IMMEDIATELY AND DO NOT USE THEM ANY FURTHER.</h2>
          <h2 className='mt-[2rem]'>Except as otherwise noted, this Agreement constitutes the entire and only Agreement between you and Outpost Healthcare Corporation and supersedes all other Agreements, representations, warranties, and understandings with respect to our Platform, and the subject matter contained herein. However, for you to use our Platform, you may also be required to agree to additional terms and conditions. Those additional terms and conditions will be incorporated into this Agreement unless otherwise stated.</h2>
          <h2 className='text-[20px] font-bold mt-5'>4. Use of Services</h2>
          <h2 className='mt-1'>To use our Platform, it is mandatory that you register a Member account with us. You are legally responsible for ensuring that you use the Platform in compliance with all Terms and Conditions of Use herein contained. The Platform utilizes tools for geolocation. Permitted Use of the Platform in the jurisdiction where you are located at the time of a Consultation, is subject to the legal permissions and regulations of that jurisdiction. Any Use not permitted by the laws or regulations applicable where you are located at the time of a Consultation, constitutes a violation of the Terms and conditions for the Platform, and will result in immediate termination of the Member account. You agree to enable and authorize our geolocation services in the Platform in order for Outpost Healthcare Corporation to provide care and full compliance with local laws and regulations.  As part of the registration process you may be required to provide us with personally identifiable information such as: biographic information, insurance information, banking and payment information in addition to other types of information necessary for us to create your user/member account. You may update or change your Account settings at any time.</h2>
          <h2 className='mt-[2rem]'>Your Membership is not transferable or assignable and is void where prohibited. Our Platform is intended solely for Users who are at least (18) years of age or older. Any registration by, use of, or access to our Platform by anyone under that age is unauthorized, unlicensed, and in violation of these Terms and Conditions. By using our Platform, you represent and warrant that you are (18) years of age or older and agree to abide by all the terms and conditions of this Agreement. Outpost Healthcare Corporation has sole right and discretion to determine whether to accept a Member, and may reject a Member’s registration with or without explanation.</h2>
          <h2 className='mt-[2rem]'>When you complete the registration process, you will create a username and password of your choice, that will allow you to access our Platform. You agree to maintain the confidentiality of your password and are fully responsible for all liability and damages resulting from your failure to maintain that confidentiality as well as all activities that occur through the use of your password. You agree to immediately notify us of any unauthorized use of your password or any other breach of security. You agree that our Platform cannot and will not be liable for any loss or damage arising from your failure to comply with password security as discussed herein.</h2>
          <h2 className='mt-[1rem]'><strong>Violating Laws and Regulations:</strong> You are required to comply with all applicable laws, regulations, and rules when using our Services. This includes adhering to local, state, national, and international laws that govern online conduct, data protection, and privacy. Violating these laws could result in legal consequences and may lead to the suspension or termination of your access to our Services. We reserve the right to report any illegal activities to the relevant authorities.</h2>
          <h2 className='mt-[1rem]'><strong>Infringing on Rights:</strong> You must respect the rights of others, including intellectual property rights (such as copyrights, trademarks, and patents) and privacy rights. Infringement can occur through unauthorized use, reproduction, or distribution of proprietary content, such as software, images, text, or other creative works. Additionally, you should not use our Services to violate or infringe upon any other proprietary rights, including trade secrets and personal data. Engaging in such activities undermines trust and can lead to legal action against you.</h2>
          <h2 className='mt-[1rem]'><strong>Submitting False or Misleading Information:</strong> Accuracy and honesty are critical when using our Services. Submitting false, misleading, or fraudulent information, whether about your identity, credentials, or any other details, is strictly prohibited. Providing accurate and truthful information ensures the proper functioning of our Services and helps maintain a trustworthy environment for all users. Misrepresentation can lead to penalties, including account suspension or legal repercussions.</h2>
          <h2 className='mt-[1rem]'><strong>Unauthorized Use:</strong> The Services must be used in a manner that does not harm, disable, overburden, or impair their functionality or performance. This includes refraining from any activity that disrupts the normal operation of the Services or negatively affects other users. Unauthorized use of the Services, including exploiting vulnerabilities or engaging in activities that degrade the user experience, is prohibited. Such actions can lead to immediate termination of access and potential legal consequences.</h2>
          <h2 className='mt-[1rem]'><strong>Unauthorized Access:</strong> Attempting to gain unauthorized access to our systems, networks, or accounts is a serious violation. This includes hacking, cracking, or using other methods to bypass security measures to access private information or system resources. Such actions are illegal and can result in severe penalties. We implement stringent security measures to protect our Services, and any attempt to compromise these measures will be addressed with appropriate legal action.</h2>
          <h2 className='mt-[1rem]'><strong>Transmission of Harmful Code:</strong> You must not introduce or transmit any harmful or disruptive code into our Services. This includes viruses, worms, trojan horses, or any other malicious software designed to damage, interfere with, or disrupt the normal operation of the Services or compromise the security of our systems. Such activities can lead to data breaches, loss of functionality, and potential harm to other users. We actively monitor for malicious activities and take necessary actions to protect our platform and its users.</h2>
          <h2 className='text-[20px] font-bold mt-5'>5. User Content</h2>
          <h2 className='mt-3'><strong>Content Ownership:</strong> You retain ownership of any content you submit through our Services, including but not limited to text, images, and other materials ("User Content"). By submitting User Content, you grant CareSync Med a non-exclusive, worldwide, royalty-free, transferable license to use, reproduce, modify, distribute, and display such User Content in connection with the Services.</h2>
          <h2 className='mt-3'><strong>Is Defamatory, Obscene, Pornographic, or Offensive:</strong> User Content must adhere to community standards and not include material that is defamatory, obscene, pornographic, or otherwise offensive. Defamatory content includes false statements that could harm the reputation of individuals or entities. Obscene and pornographic content refers to material that is explicit in nature and unsuitable for general audiences. Offensive content encompasses any material that is discriminatory, harassing, or otherwise inappropriate. Submitting such content can harm others and is not tolerated.</h2>
          <h2 className='mt-3'><strong>Promotes Violence or Discrimination:</strong> User Content must not promote or incite violence, hatred, or discrimination against individuals or groups based on attributes such as race, ethnicity, religion, gender, sexual orientation, disability, or any other characteristic. Content that advocates violence or seeks to harm others, or that fosters discriminatory attitudes, is strictly prohibited. Such content undermines the values of respect and inclusion and can have serious legal and ethical implications.</h2>
          <h2 className='mt-3'><strong>Infringes on Intellectual Property Rights:</strong> Any User Content you submit must not infringe upon the intellectual property rights of others. This includes content that violates copyrights, trademarks, patents, or trade secrets. Intellectual property infringement can occur through the unauthorized use, reproduction, distribution, or display of copyrighted materials, brand logos, or patented inventions. Ensuring that your content respects the rights of original creators and rights holders is essential for maintaining a legal and respectful environment.</h2>
          <h2 className='mt-3'><strong>Contains Viruses, Malware, or Other Harmful Components:</strong> User Content must be free from viruses, malware, spyware, or any other harmful components that could compromise the security or functionality of our Services or the devices of other users. This includes files or code designed to disrupt, damage, or gain unauthorized access to systems or data. Submitting such content not only poses security risks but can also damage the trust and integrity of our platform.</h2>
          <h2 className='mt-3'><strong>Violates Any Law or Regulation:</strong> User Content must comply with all applicable laws and regulations. This includes local, national, and international laws governing content and online behavior. Violations may include, but are not limited to, illegal activities such as fraud, copyright infringement, and the distribution of prohibited content. Adhering to legal requirements ensures the lawful operation of our Services and protects both users and the platform from legal issues.</h2>
          <h2 className='text-[20px] font-bold mt-5'>6. Privacy Policy</h2>
          <h2 className='mt-2'>Your use of our Services is also governed by our Privacy Policy, which describes how we collect, use, and protect your personal information. By using our Services, you consent to our collection and use of your information as described in the Privacy Policy <Link to='/privacy_policy' className='text-[#0bcbec] font-semibold underline'>here.</Link></h2>
          <h2 className='text-[20px] font-bold mt-5'>7. Fees and Payment</h2>
          <h2 className='mt-2'>‍You represent and warrant that if you are purchasing something from us, (i) any payment information you supply is true and complete, (ii) charges incurred by you will be honored by your bank or credit card company, (iii) you will pay the charges incurred by you at the posted prices, including any applicable taxes, and (iv) if your initial payment method is dishonored, you will still pay the incurred charges, including any surcharge we may incur due to the dishonored payment.</h2>
          <h2 className='mt-[2rem] mb-[1.5rem] text-[#000] font-extrabold'>Payment and Refund Management</h2>
          <h2 className='mt-3 font-bold'>YOU AGREE AS A MEMBER OF THE CARESYNC MED HEALTHCARE PLATFORM THAT YOU WILL PAY CARESYNC MED HEALTHCARE PROFESSIONALS OR CARESYNC MED HEALTHCARE PLATFORM FOR A CONSULTATION OR USE OF THE PLATFORM THROUGH CARESYNC MED'S HEALTHCARE PLATFORM AND AFFILIATES AND PARTNERS AND THAT YOU WILL NOT PAY ANY HEALTHCARE PROFESSIONAL DIRECTLY OR INDIRECTLY FOR A CONSULTATION. ALL PAYMENTS MUST BE MADE THROUGH CARESYNC MED HEALTHCARE CORPORATION AND AFFILIATES OR PARTNERS.</h2>
          <h2 className='mt-[1.5rem]'>You also agree as a Member and individual that you will not attempt to communicate; verbally, written, or electronically with any Outpost Healthcare employee or Healthcare Professional through any means other than the Platform.</h2>
          <h2 className='mt-[1.5rem]'><strong>Service Fees:</strong> Some aspects of our Services may require payment of fees. You agree to pay all applicable fees in connection with your use of the Services. All fees are non-refundable unless otherwise stated.</h2>
          <h2 className='mt-3'><strong>Payment Methods:</strong> We accept various forms of payment, as indicated on our platform. You authorize us to charge your chosen payment method for any fees due.</h2>
          <h2 className='mt-3'><strong>Subscription Services:</strong> If you subscribe to any recurring services, you agree that your subscription will automatically renew at the end of each subscription period unless you cancel your subscription before the renewal date.</h2>
          <h2 className='text-[20px] font-bold mt-5'>8. Intellectual Property</h2>
          <h2 className='mt-3'><strong>Ownership:</strong> All intellectual property rights in the Services, including but not limited to trademarks, logos, service marks, text, graphics, software, and other content, are owned by CareSync Med or our licensors. You are granted a limited, non-exclusive, non-transferable license to access and use the Services for your personal, non-commercial use.</h2>
          <h2 className='mt-3'><strong>Restrictions:</strong> You may not modify, distribute, reproduce, publish, license, create derivative works from, transfer, or sell any content or information obtained from the Services without our prior written consent.</h2>
          <h2 className='text-[20px] font-bold mt-5'>9. Termination</h2>
          <h2 className='mt-2'>We reserve the right to terminate or suspend your access to the Services at any time, with or without notice, for any reason, including if we believe you have violated these Terms or engaged in conduct that could harm us, our users, or third parties. Upon termination, your right to use the Services will immediately cease, and you must cease all use of the Services.</h2>
          <h2 className='text-[20px] font-bold mt-5'>10. Disclaimers and Limitation of Liability</h2>
          <h2 className='mt-3'><strong>Disclaimers:</strong> The Services are provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Services will be uninterrupted, error-free, or secure.</h2>
          <h2 className='mt-3'><strong>Limitation of Liability:</strong> To the fullest extent permitted by law, CareSync Med and its affiliates, officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (i) your use or inability to use the Services; (ii) any unauthorized access to or use of our servers and/or any personal information stored therein; (iii) any interruption or cessation of transmission to or from the Services; (iv) any bugs, viruses, trojan horses, or the like that may be transmitted to or through our Services by any third party; or (v) any errors or omissions in any content or for any loss or damage incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available through the Services.</h2>
          <h2 className='mt-3'><strong>Maximum Liability:</strong> In no event shall our total liability to you for all damages, losses, and causes of action exceed the amount you have paid CareSync Med in the last six (6) months, or, if greater, one hundred dollars ($100).</h2>
          <h2 className='text-[20px] font-bold mt-5'>11. Indemnification</h2>
          <h2 className='mt-2'>You agree to defend, indemnify, and hold harmless CareSync Med, its affiliates, officers, directors, employees, and agents from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Services; (ii) your violation of any term of these Terms; (iii) your violation of any third-party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that your User Content caused damage to a third party.</h2>
          <h2 className='text-[20px] font-bold mt-5'>12. Governing Law and Dispute Resolution</h2>
          <h2 className='mt-3'><strong>Governing Law:</strong> These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which CareSync Med operates, without regard to its conflict of law principles.</h2>
          <h2 className='mt-3'><strong>Dispute Resolution:</strong> Any disputes arising out of or in connection with these Terms or the use of the Services shall be resolved through binding arbitration conducted by a single arbitrator in accordance with the rules of the American Arbitration Association. The arbitration shall take place in the jurisdiction in which CareSync Med operates, and the arbitrator's decision shall be binding and may be entered as a judgment in any court of competent jurisdiction.</h2>
          <h2 className='text-[20px] font-bold mt-5'>13. Changes to Terms</h2>
          <h2 className='mt-2'>‍We reserve the right to change these Terms and Conditions at any time by giving you advance notice of the changes by email or in writing. We will also post these changes on our Platform and website. These changes will become effective 30 days after receipt of the notice. To avoid doubt, no unilateral amendment will retroactively change agreed dispute-resolution provisions of these Terms and Conditions, if any, including, for example, arbitration provisions for then-pending disputes unless the parties expressly agree otherwise. Your continued use of our Platform after any change to these Terms and Conditions and our notifying you will constitute your acceptance of such change. If you do not agree with the changes to these Terms and Conditions, you can choose to discontinue the use of our Platform.</h2>
          <h2 className='text-[20px] font-bold mt-5'>14. Miscellaneous</h2>
          <h2 className='mt-3'><strong>Severability:</strong> If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.</h2>
          <h2 className='mt-3'><strong>Entire Agreement:</strong> These Terms, together with our Privacy Policy, constitute the entire agreement between you and CareSync Med regarding the use of the Services.</h2>
          <h2 className='mt-3'><strong>Waiver:</strong> Our failure to enforce any right or provision of these Terms shall not be deemed a waiver of such right or provision.</h2>
          <h2 className='mt-[3rem] text-[17px]'>Copyright © CareSync Med Corporation 2024. www.caresyncmed.com</h2>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default Terms_Conditions